-- Security hardening: application password policy + RLS fixes.
-- Applied directly to Supabase project pqjrmtkfgwoocbvmwbby.
--
-- Password policy is enforced in the application signup schema:
-- 12-128 chars, lower, upper, digit and symbol.
-- Supabase Auth remains the authoritative password storage/authentication layer.
--
-- RLS hardening:
-- * conversations are readable only by members
-- * conversation_members are readable/inserable only for the current legacy user
-- * post_stats and post_distribution are not directly readable by arbitrary users
-- * privileged feed/DM implementations live in the non-exposed private schema
-- * public RPC wrappers are SECURITY INVOKER and restricted to authenticated users
