-- Phase 3: interactions, collections, notification triggers, and auth-to-legacy user bridge.
alter table public.users add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;
create or replace function private.bridge_auth_user() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.users(auth_user_id,username,display_name,password_hash,bio,created_at)
 values(new.id,coalesce(nullif(new.raw_user_meta_data->>'username',''),'user_'||substr(replace(new.id::text,'-',''),1,10)),coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Yuniko User'),'','',now())
 on conflict(auth_user_id) do nothing; return new;
end; $$;
drop trigger if exists bridge_auth_user on auth.users;
create trigger bridge_auth_user after insert on auth.users for each row execute function private.bridge_auth_user();

create table if not exists public.collections(id bigint generated by default as identity primary key,user_id integer not null references public.users(id) on delete cascade,name text not null,created_at timestamptz not null default now(),unique(user_id,name));
alter table public.post_engagements add constraint post_engagements_user_post_unique unique(user_id,post_id);
alter table public.post_engagements enable row level security;
drop policy if exists engagement_select_own on public.post_engagements;
create policy engagement_select_own on public.post_engagements for select to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
drop policy if exists engagement_insert_own on public.post_engagements;
create policy engagement_insert_own on public.post_engagements for insert to authenticated with check(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
drop policy if exists engagement_update_own on public.post_engagements;
create policy engagement_update_own on public.post_engagements for update to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid()))) with check(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
drop policy if exists engagement_delete_own on public.post_engagements;
create policy engagement_delete_own on public.post_engagements for delete to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
alter table public.comments add column if not exists parent_id integer;
alter table public.comments add column if not exists deleted_at timestamptz;
alter table public.comments add column if not exists like_count integer not null default 0;
alter table public.comments enable row level security;
drop policy if exists comments_select_auth on public.comments;
create policy comments_select_auth on public.comments for select to authenticated using(deleted_at is null);
drop policy if exists comments_insert_auth on public.comments;
create policy comments_insert_auth on public.comments for insert to authenticated with check(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
drop policy if exists comments_update_auth on public.comments;
create policy comments_update_auth on public.comments for update to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid()))) with check(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
alter table public.notifications enable row level security;
drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications for select to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications for update to authenticated using(user_id=(select id from public.users where auth_user_id=(select auth.uid()))) with check(user_id=(select id from public.users where auth_user_id=(select auth.uid())));
create or replace function private.sync_engagement_counters() returns trigger language plpgsql security definer set search_path='' as $$
begin
 update public.posts set likes=(select count(*) from public.post_engagements e where e.post_id=coalesce(new.post_id,old.post_id) and e.liked),saves=(select count(*) from public.post_engagements e where e.post_id=coalesce(new.post_id,old.post_id) and e.saved),shares=(select count(*) from public.post_engagements e where e.post_id=coalesce(new.post_id,old.post_id) and e.shared) where id=coalesce(new.post_id,old.post_id); return coalesce(new,old);
end; $$;
drop trigger if exists engagement_counter_sync on public.post_engagements;
create trigger engagement_counter_sync after insert or update or delete on public.post_engagements for each row execute function private.sync_engagement_counters();
create or replace function private.notify_engagement() returns trigger language plpgsql security definer set search_path='' as $$
declare target integer; actor integer; pid integer; typ text; msg text;
begin target=(select user_id from public.posts where id=new.post_id); actor=new.user_id; pid=new.post_id;
if new.liked and not coalesce(old.liked,false) then typ='like';msg='liked your post';elsif new.shared and not coalesce(old.shared,false) then typ='share';msg='shared your post';else return new;end if;
if target is not null and target<>actor then insert into public.notifications(user_id,actor_id,type,post_id,message) values(target,actor,typ,pid,msg);end if;return new;end; $$;
drop trigger if exists engagement_notification on public.post_engagements;
create trigger engagement_notification after insert or update on public.post_engagements for each row execute function private.notify_engagement();
create or replace function private.notify_comment() returns trigger language plpgsql security definer set search_path='' as $$
declare target integer;begin target=(select user_id from public.posts where id=new.post_id);if target is not null and target<>new.user_id then insert into public.notifications(user_id,actor_id,type,post_id,message) values(target,new.user_id,'comment',new.post_id,'commented on your post');end if;return new;end; $$;
drop trigger if exists comment_notification on public.comments;
create trigger comment_notification after insert on public.comments for each row execute function private.notify_comment();
