-- Yuniko phases 1-2: foundations, auth/profile integration, social/content base.
-- Applied to the connected Supabase project before this file was committed.

create extension if not exists pg_trgm;

alter table public.posts
  add column if not exists author_id uuid references auth.users(id) on delete cascade,
  add column if not exists visibility text not null default 'public',
  add column if not exists status text not null default 'ready';

alter table public.follows
  add column if not exists follower_uuid uuid references auth.users(id) on delete cascade,
  add column if not exists following_uuid uuid references auth.users(id) on delete cascade;

create unique index if not exists follows_uuid_pair_unique on public.follows (follower_uuid, following_uuid)
where follower_uuid is not null and following_uuid is not null;

create index if not exists posts_author_created_idx on public.posts (author_id, created_at desc);
create index if not exists posts_created_ready_idx on public.posts (created_at desc) where deleted_at is null and status = 'ready';
create index if not exists follows_follower_uuid_idx on public.follows (follower_uuid);
create index if not exists follows_following_uuid_idx on public.follows (following_uuid);

create table if not exists public.post_media (
  id bigint generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  url text not null,
  width integer,
  height integer,
  blurhash text,
  position integer not null default 0,
  status text not null default 'ready',
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  post_id integer references public.posts(id) on delete set null,
  type text not null,
  weight numeric not null default 1,
  country_code text,
  session_id text,
  dwell_ms integer,
  created_at timestamptz not null default now()
);

alter table public.post_media enable row level security;
alter table public.events enable row level security;

revoke all on public.post_media from anon, authenticated;
grant select, insert, update, delete on public.post_media to authenticated;
revoke all on public.events from anon, authenticated;
grant select, insert on public.events to authenticated;

drop policy if exists post_media_select_authenticated on public.post_media;
create policy post_media_select_authenticated on public.post_media for select to authenticated
using (exists (select 1 from public.posts p where p.id=post_media.post_id and p.deleted_at is null and p.status='ready'));

drop policy if exists post_media_insert_owner on public.post_media;
create policy post_media_insert_owner on public.post_media for insert to authenticated
with check (exists (select 1 from public.posts p where p.id=post_media.post_id and p.author_id=(select auth.uid())));

drop policy if exists events_select_self on public.events;
create policy events_select_self on public.events for select to authenticated using ((select auth.uid())=user_id);

drop policy if exists events_insert_self on public.events;
create policy events_insert_self on public.events for insert to authenticated with check ((select auth.uid())=user_id);

drop policy if exists posts_select_authenticated on public.posts;
create policy posts_select_authenticated on public.posts for select to authenticated using (
  deleted_at is null and status='ready' and (
    visibility='public' or author_id=(select auth.uid()) or exists (
      select 1 from public.follows f where f.follower_uuid=(select auth.uid())
      and f.following_uuid=posts.author_id and f.status='accepted'
    )
  )
);

drop policy if exists posts_insert_owner on public.posts;
create policy posts_insert_owner on public.posts for insert to authenticated with check ((select auth.uid())=author_id);

drop policy if exists posts_update_owner on public.posts;
create policy posts_update_owner on public.posts for update to authenticated
using ((select auth.uid())=author_id) with check ((select auth.uid())=author_id);

drop policy if exists posts_delete_owner on public.posts;
create policy posts_delete_owner on public.posts for delete to authenticated using ((select auth.uid())=author_id);

drop policy if exists follows_select_participant on public.follows;
create policy follows_select_participant on public.follows for select to authenticated
using (follower_uuid=(select auth.uid()) or following_uuid=(select auth.uid()));

drop policy if exists follows_insert_self on public.follows;
create policy follows_insert_self on public.follows for insert to authenticated
with check ((select auth.uid())=follower_uuid and follower_uuid<>following_uuid);

drop policy if exists follows_update_self on public.follows;
create policy follows_update_self on public.follows for update to authenticated
using ((select auth.uid())=follower_uuid) with check ((select auth.uid())=follower_uuid);

drop policy if exists follows_delete_self on public.follows;
create policy follows_delete_self on public.follows for delete to authenticated using ((select auth.uid())=follower_uuid);

create schema if not exists private;

create or replace function private.sync_profile_counts()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if tg_op='INSERT' and new.following_uuid is not null and new.status='accepted' then
    update public.profiles set following_count=following_count+1,updated_at=now() where id=new.follower_uuid;
    update public.profiles set follower_count=follower_count+1,updated_at=now() where id=new.following_uuid;
  elsif tg_op='DELETE' and old.following_uuid is not null and old.status='accepted' then
    update public.profiles set following_count=greatest(0,following_count-1),updated_at=now() where id=old.follower_uuid;
    update public.profiles set follower_count=greatest(0,follower_count-1),updated_at=now() where id=old.following_uuid;
  end if;
  return coalesce(new,old);
end;
$$;

revoke execute on function private.sync_profile_counts() from public,anon,authenticated;
drop trigger if exists follows_profile_counts on public.follows;
create trigger follows_profile_counts after insert or delete on public.follows for each row execute function private.sync_profile_counts();

create or replace function private.sync_post_count()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if tg_op='INSERT' then
    update public.profiles set post_count=post_count+1,updated_at=now() where id=new.author_id;
  elsif tg_op='DELETE' then
    update public.profiles set post_count=greatest(0,post_count-1),updated_at=now() where id=old.author_id;
  end if;
  return coalesce(new,old);
end;
$$;

revoke execute on function private.sync_post_count() from public,anon,authenticated;
drop trigger if exists posts_profile_count on public.posts;
create trigger posts_profile_count after insert or delete on public.posts for each row execute function private.sync_post_count();

create or replace function private.emit_follow_event()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.events(user_id,type,weight)
  values(new.follower_uuid,case when new.status='pending' then 'follow.requested' else 'follow.created' end,1);
  return new;
end;
$$;

revoke execute on function private.emit_follow_event() from public,anon,authenticated;
drop trigger if exists follows_event on public.follows;
create trigger follows_event after insert on public.follows for each row execute function private.emit_follow_event();

create or replace function public.handle_auth_profile()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.profiles(id,username,display_name)
  values(
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username',''),'user_'||substr(replace(new.id::text,'-',''),1,10)),
    coalesce(nullif(new.raw_user_meta_data->>'display_name',''),coalesce(new.email,'Yuniko User'))
  )
  on conflict(id) do nothing;
  return new;
end;
$$;

revoke execute on function public.handle_auth_profile() from public,anon,authenticated;
drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile after insert on auth.users for each row execute function public.handle_auth_profile();

create index if not exists profiles_username_trgm_idx on public.profiles using gin (username gin_trgm_ops);
create index if not exists profiles_display_name_trgm_idx on public.profiles using gin (display_name gin_trgm_ops);
