-- Phase 3: interactions, comments, saves/collections, shares through post_engagements, RLS, counters, notifications.
-- Applied to the connected Supabase project.
create table if not exists public.collections(
 id bigint generated by default as identity primary key,
 user_id integer not null references public.users(id) on delete cascade,
 name text not null,
 created_at timestamptz not null default now(),
 unique(user_id,name)
);
alter table public.post_engagements add constraint post_engagements_user_post_unique unique(user_id,post_id);
alter table public.comments add column if not exists parent_id integer;
alter table public.comments add column if not exists deleted_at timestamptz;
alter table public.comments add column if not exists like_count integer not null default 0;